// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface IServiceType {
  id:                    number;
  name:                  string;
  description           :string;
  positiveNegative:      number;
  isRegisterTransaction: boolean;
  taxItems:              boolean;
  showOrderType:         boolean;
  retailServiceType:     number;
  managerRequired:       number;
  showTipOption:         number;
  printerName:           string;
  icon       :           string;
  apiOrder          :    boolean;
  onlineOrder       :    boolean;
  promptScheduleTime  :  boolean;
  deliveryService     : boolean;
  orderMinimumTotal  :  number;
  instructions:          string;
  shippingInstructions : string;
  scheduleInstructions : string;
}
