// Generated by https://quicktype.io
// Generated by https://quicktype.io
import { ItemBasic } from "src/app/modules/admin/report-designer/interfaces/reports";
import { IMenuItem } from "../menu/menu-products";

export interface IServiceType {
  id:                    number;
  image: string;
  name:                  string;
  description           :string;
  positiveNegative:      number;
  isRegisterTransaction: boolean;
  taxItems:              boolean;
  showOrderType:         boolean;
  retailType       :     boolean;
  managerRequired:       number;
  showTipOption:         number;
  printerName:           string;
  icon       :           string;
  apiOrder          :    boolean;
  onlineOrder       :    boolean;
  promptScheduleTime  :  boolean;
  deliveryService     : boolean;
  orderMinimum        :  number;
  instructions:          string;
  shippingInstructions : string;
  scheduleInstructions : string;
  defaultProductID1    : number;
  defaultProductID2    : number;
  functionChoice      : number;
  functionChoice2     : number;
  functionChoice3     : number;
  requireNumOfGuests  : number;
  promptForOrderName  : number;
  filterType          : number;
  allowRequestPrep      : boolean; //allowrequestPrep
  serviceColor   : string;
  listFontColor  : string;
  buttonColor    : string;
  assignOrderToCloser : boolean;
  assignCloserToOrder : boolean;
  onOrderClose: number;
  actionOne   : number;
  actionTwo   : number;
  menuItem1   : IMenuItem;
  menuItem2   : IMenuItem;
  resaleType  : boolean;
  headerOrder: boolean;
  json: string; //converts to serviceTypeFeatures
  serviceTypeFeatues: ServiceTypeFeatures;
  allRequestPrep: number;
}

export interface ServiceTypeFeatures {
  weekDays: any[];
  hoursAndDayID: any[];
  seatEnabled: boolean;
  icon: string;
  sortOrder: number;
  nameStringPairs: NameStringListPair[]; // New property
  addressList: ServiceAddress[];
  weekDayTimeValidator: ScheduleValidator;
  dateRanges          : ScheduleDateValidator;
  excludedDates       : ScheduleDateValidator;
  metaTags            : string[]
}

export interface ServiceAddress {
  name: string;
  contactName: string;
  phone: string;
  address: string;
  unit: string;
  city: string;
  state: string;
  zip: string;
}

export interface NameStringListPair {
  name: string;
  values: string[];
}

export interface weekDays {
  id: number;
  name: string;
}

//24 hours
export interface hoursAndDayID {
  hours: [];
}

export interface IServiceTypePOSPut {
  id:                    number;
  name:                  string;
  description           :string;
  positiveNegative:      number;
  isRegisterTransaction: boolean;
  taxItems:              boolean;
  showOrderType:         boolean;
  retailServiceType:     number;
  managerRequired:       number;
  showTipOption:         number;
  printerName:           string;
  icon       :           string;
  apiOrder          :    boolean;
  onlineOrder       :    boolean;
  promptScheduleTime  :  boolean;
  deliveryService     : boolean;
  orderMinimumTotal  :  number;
  instructions:          string;
  shippingInstructions : string;
  scheduleInstructions : string;
  defaultProductID1    : number;
  defaultProductID2    : number;
  functionChoice      : number;
  functionChoice2     : number;
  functionChoice3     : number;
  requireNumOfGuests  : number;
  promptForOrderName  : number;
  filterType          : number;
  json                : string
}

export interface DayTimeRangeValidator {
  day: string;            // e.g., 'Monday'
  timeRanges: { startTime: string, endTime: string }[];  // Multiple ranges per day
  disabled?: boolean;
}

export interface ScheduleValidator {
  week: DayTimeRangeValidator[];    // Array to store schedules for each day
}

export interface DateRangeValidator {
  startDate: string; // Start date of the range
  endDate: string;   // End date of the range
}

export interface ScheduleDateValidator {
  allowedDates: DateRangeValidator[];
}
