import { Injectable } from '@angular/core';
import { Observable, } from 'rxjs';
import { IMETRCSales } from 'src/app/_interfaces/transactions/metrc-sales';
import { HttpClient } from '@angular/common/http';
import { AuthenticationService } from '../../_services/system/authentication.service';
import { ISite } from 'src/app/_interfaces';
import { SitesService } from '../../_services/reporting/sites.service';

// Generated by https://quicktype.io

import {
  METRCItems,
  METRCItemsCategories,
  MetrcItemsBrands,
  METRCItemsCreate,
  METRCItemsUpdate
} from '../../_interfaces/metrcs/items';

@Injectable({
  providedIn: 'root'
})
export class MetrcItemsCategoriesService {

  constructor( private http: HttpClient,
    private auth: AuthenticationService,
    private sitesService: SitesService,
   ) {}

  importItemCategories(site: ISite): Observable<METRCItemsCategories[]> {

    const controller = '/MetrcCategories/'

    const endPoint   = `GetImportItemCategories`

    const parameters = `?siteName=${site.name}`

    const url        = `${site.url}${controller}${endPoint}${parameters}`

    return this.http.get<METRCItemsCategories[]>(url);

  }

  getCategories(): Observable<METRCItemsCategories[]> {

    const site = this.sitesService.getAssignedSite();

    const controller = '/MetrcCategories/'

    const endPoint = `GetMetrcCategories`

    const parameters = ''

    const url = `${site.url}${controller}${endPoint}${parameters}`

    return this.http.get<METRCItemsCategories[]>(url);

  }

  getCategory(id: any): Observable<METRCItemsCategories> {

    const site = this.sitesService.getAssignedSite();

    const controller = '/MetrcCategories/'

    const endPoint = `GetMetrcCategory`

    const parameters = `?id=${id}`

    const url = `${site.url}${controller}${endPoint}${parameters}`

    return this.http.get<METRCItemsCategories>(url);

  }

  putCategory(id: number, mETRCItemsCategories: METRCItemsCategories): Observable<METRCItemsCategories> {

    const site = this.sitesService.getAssignedSite();

    const controller = '/MetrcCategories/'

    const endPoint = 'PutMetrcCategory'

    const parameters = '?id=${id}'

    const url = `${site.url}${controller}${endPoint}${parameters}`

    return this.http.put<METRCItemsCategories>(url, mETRCItemsCategories);

  }

  postCategory(mETRCItemsCategories: METRCItemsCategories): Observable<METRCItemsCategories> {

    const site = this.sitesService.getAssignedSite();

    const controller = '/MetrcCategories/'

    const endPoint = 'PostMetrcCategory'

    const parameters = ''

    const url = `${site.url}${controller}${endPoint}${parameters}`

    return this.http.post<METRCItemsCategories>(url, mETRCItemsCategories);

  }


}
