import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AuthenticationService } from '../system/authentication.service';
import { Observable  } from 'rxjs';
import {  ISite }  from 'src/app/_interfaces';
import {  IItemBasicB } from './menu.service';
import { UseGroupTax, UseGroups } from './use-groups.service';

// Generated by https://quicktype.io

export interface IItemTypesList {
  id:                  number;
  name:                string;
  taxable:             number;
  type:                string;
  weightedItem:        boolean;
  expirationRequired:  boolean;
  labelRequired:       boolean;
  enabled:             boolean;
  ageRequirement:      number;
  sortOrder:           number;
  useType:             string;
  useGroupID:           number;
  itemType_Categories_List: itemType_Categories_List[];
  brandItemCount      : BrandItemCount[];
  packageType         : string;
}

export interface BrandItemCount {
  id        : number;
  name      : string;
  itemTypeID: number;
  itemCount : number;
}

export interface itemType_Categories_List {
  itemTypeName: string;
  id:           number;
  itemTypeID:   number;
  categoryID:   number;
  name:         string;
  itemCounts:   ItemCounts;
}

export interface ItemType_Categories_Reference {
  id          : number;
  itemTypeID  : number;
  categoryID  : number;
  name        : string;
  itemTypeName: string;
}

export interface itemType_Categories
{
    id          : number;
    categoryID  : number;
    itemTypeID  : number;
    itemCounts   : ItemCounts;
}

// Generated by https://quicktype.io

export interface IItemType {
  id:                  number;
  name:                string;
  type:                string;
  weightedItem:        boolean;
  expirationRequired:  boolean;
  labelRequired:       boolean;
  ageRequirement:      number;
  sortOrder:           number;
  enabled:             boolean;
  useType:             string;
  useGroupID:          number;
  icon:                string;
  imageName:           string;
  taxable:             number;
  prepTicketID        :number;
  labelTypeID         :number;
  printerName:         string;
  printLocationID :    number;
  itemType_Categories: ItemTypeCategory[];
  requiresSerial      :boolean;
  packageType         :string;
}

export interface FlatRateTax {
  id:                number;
  name:              string;
  flatRateTaxValues: FlatRateTaxValue[];
}

export interface FlatRateTaxValue {
  id:            number;
  flatRateTaxID: number;
  rateStart:     number;
  rateEnd:       number;
  fee:           number;
}

export interface ItemTypeCategory {
  id:         number;
  categoryID: number;
  itemTypeID: number;
  itemCounts : ItemCounts;
}

export interface ItemCounts {
  id       : number;
  name     : string; //"sample string 2",
  itemCount: number;
}

export interface Tax {
  id:     number;
  amount: number;
  name:   string;
}

@Injectable({
  providedIn: 'root'
})
export class ItemTypeService {

packageType = ['Not-Specified', 'Marijuana Weighed', 'Marijuana - Packaged', 'Medicine - Weighed', 'Medicine Each', 'Seeds', 'Plants', 'Seeds', 'Concentrates', 'Solid', 'Liquid', 'Extract']
type       = [
   'grouping',
   'restaurant',
   'discounts',
   'tobacco',
   'cannabis',
   'retail',
   'med-cannabis',
   'grocery',
   'retail liquor',
   'service liquor'
  ]
useType = ['product', 'adjustment', 'category']

site: ISite;
constructor(private http: HttpClient,
            private auth: AuthenticationService) { }


  delete(site: ISite, id: number): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${id}`;

    const endPoint = 'deleteItemType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.delete<IItemType>(url);

  }

  deleteItems(site: ISite, items: IItemType[]): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = ``;

    const endPoint = 'DeleteItemTypes';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.post<IItemType[]>(url, items);

  }


  initItemTypes(site: ISite, iItemType: IItemType[]): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = '';

    const endPoint ='postItemTypeList';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.post<IItemType[]>(url, iItemType);

  }


  getBasicTypes(site: ISite): Observable<IItemBasicB[]> {

    const controller = '/ItemTypes/';

    const parameters = '';

    const endPoint = 'GetBasicTypes';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemBasicB[]>(url);

  }

  getItemTypes(site: ISite): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = '';

    const endPoint = 'GetItemTypes';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemType[]>(url);

  }

  getItemTypesByType(site: ISite, type: string): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = `?type=${type}`;

    const endPoint = 'GetItemTypesByType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemType[]>(url);

  }

  getItemTypesByUseType(site: ISite, useType: string): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = `?useType=${useType}`;

    const endPoint = 'GetItemTypesByUseType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemType[]>(url);

  }


  getItemTypeCategoriesReadOnlyList(site: ISite): Observable<IItemTypesList[]> {

    const controller = '/ItemTypes/';

    const parameters = ``;

    const endPoint = 'GetItemTypeCategoriesReadOnlyList';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemTypesList[]>(url);

  }

  getBasicTypesByUseType(site: ISite, useType: string): Observable<any[]> {

    const controller = '/ItemTypes/';

    const parameters = `?useType=${useType}`;

    const endPoint = 'getBasicTypesByUseType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<any[]>(url);

  }



  getItemType(site: ISite, id: number): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${id}`;

    const endPoint = 'getItemType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemType>(url);

  }


  getItemTypeCategories(site: ISite, id: number): Observable<ItemType_Categories_Reference[]> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${id}`;

    const endPoint = 'getItemTypeCategories';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<ItemType_Categories_Reference[]>(url);

  }


  getItemTypeCategoriesAll(site: ISite): Observable<ItemType_Categories_Reference[]> {

    const controller = '/ItemTypes/';

    const parameters = ``;

    const endPoint = 'getItemTypeCategoriesAll';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<ItemType_Categories_Reference[]>(url);

  }

  putItemTypesList(site: ISite, iItemType: IItemType[]): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = '';

    const endPoint = 'putItemTypeList';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.put<IItemType[]>(url, iItemType);

  }

  putItemType(site: ISite, itemType: IItemType): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${itemType.id}`;

    const endPoint = 'putItemType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;
    console.log(url)
    return  this.http.put<IItemType>(url, itemType);

  }

  postItemType(site: ISite, itemType: IItemType): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = ``;

    const endPoint = 'PostItemType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.post<IItemType>(url, itemType);

  }

  saveItemType(site: ISite, itemType: IItemType): Observable<IItemType> {

      if ( !itemType.id || itemType.id == 0) {
        return  this.postItemType(site, itemType)
      }
      if (itemType.id != 0) {
        return  this.putItemType(site, itemType)
      }

  }


  putItemTypeNoChildren(site: ISite, itemType: IItemType): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${itemType.id}`;

    const endPoint = 'putItemTypeNoChildren';

    const url = `${site.url}${controller}${endPoint}${parameters}`;
    console.log(url)
    return  this.http.put<IItemType>(url, itemType);

  }


  saveCategories(site: ISite, id: number, categories: itemType_Categories[]): Observable<itemType_Categories[]> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${id}`;

    const endPoint = 'saveCategories';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.post<itemType_Categories[]>(url, categories);

  }



  getDefaultItemTypes(): IItemType[]  {

    let   productType  = {} as IItemType[]
    let   useGroup     = {} as UseGroups[]
    const groupsTaxes  = {} as UseGroupTax[]

    const tax          = {} as Tax
    const flatRateTax  = {} as FlatRateTax
    const categories   = {} as itemType_Categories[];
    const itemcounts   = {} as ItemCounts

        // ;4;Category;5;Sub Category;6;Department;
    productType =
      [
        {id: 1,
        labelTypeID: 0,
        prepTicketID: 0,
        printLocationID: 0,
        printerName: '',
        name : "Generic",
        taxable: 1,
        type: 'generic',
        weightedItem: false,
        expirationRequired: false,
        labelRequired: false,
        enabled: true,
        ageRequirement:0,
        sortOrder: 1,
        useType:'generic',
        icon: 'generic',
        useGroupID: 11,
        imageName: '',
        itemType_Categories: categories,
        requiresSerial: false
        ,packageType: ''
      },

        {id: 2,packageType: '',  taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0, requiresSerial: false, printerName: '',    name : "Modifier",              itemType_Categories: categories, imageName: '',       icon: 'food', useType:'product', sortOrder: 11, ageRequirement: 0,   enabled: true,     type: 'restaurant', useGroupID: 1, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 3, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',    name : "Text",                  itemType_Categories: categories, imageName: '',       icon: 'food', useType:'adjustment', sortOrder: 12, ageRequirement: 0, enabled: true,     type: 'restaurant', useGroupID: 1, weightedItem: true, expirationRequired: false, labelRequired: false, },

        {id: 4, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Category",              itemType_Categories: categories, imageName: '',       icon: 'category',useType:'category', sortOrder: 8, ageRequirement: 0, enabled: true,    type: 'grouping', useGroupID: 3, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 5,packageType: '',  taxable: 0,  labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Sub Category",          itemType_Categories: categories, imageName: '',       icon: 'group'  , useType:'category', sortOrder: 9, ageRequirement: 0, enabled: true,    type: 'grouping', useGroupID: 3,weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 6,packageType: '',  taxable: 0,  labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Department",            itemType_Categories: categories, imageName: '',       icon: 'department',useType:'category', sortOrder: 10, ageRequirement: 0, enabled: true, type: 'grouping', useGroupID: 3,weightedItem: true, expirationRequired: false, labelRequired: false, },

        {id: 8, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Discount % Entire Order",itemType_Categories: categories, imageName: '',      icon: 'coupon',useType:'adjustment', sortOrder: 13, ageRequirement: 0, enabled: true,  type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 7, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Cash Discount on Order", itemType_Categories: categories, imageName: '',      icon: 'coupon',useType:'adjustment', sortOrder: 14, ageRequirement: 0, enabled: true,  type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 9,packageType: '',  taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Quantity Off Item",     itemType_Categories: categories, imageName: '',       icon: 'coupon',useType:'adjustment', sortOrder: 15, ageRequirement: 0, enabled: true,  type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 10,packageType: '',taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Price Level 1",         itemType_Categories: categories, imageName: '',       icon: ''      ,useType:'adjustment', sortOrder: 16, ageRequirement: 0, enabled: true,  type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 11,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Price Level 2",         itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 17, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 12,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0,prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Price Level 3",         itemType_Categories: categories, imageName: '',        icon: ''      , useType:'adjustment', sortOrder: 18, ageRequirement: 0, enabled: true, type:  'discounts',  useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 13,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Discount % One Item",   itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 19, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 15,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Promo Unspecified",     itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 20, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 14,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Blind Item",            itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 21, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 16,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Point Adjustment",      itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 22, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 17,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Adjust Total ",         itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 23, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 18,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Cash Discount on Item", itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 24, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 19,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Gift Card",             itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 25,ageRequirement: 0,  enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 20,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Tare Value",            itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 27, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 21,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Gift Card Mercury",     itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 26, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 22,packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Gratuity",              itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment',  sortOrder: 28,  ageRequirement: 0, enabled:true,type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },

        {id: 23, packageType: '',taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Matrix Item",           itemType_Categories: categories, imageName: '',       icon: 'matrix',useType:'product',  sortOrder: 29, ageRequirement: 0, enabled: true, type:  'Retail', useGroupID: 5, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 24, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Retail Clothing",       itemType_Categories: categories, imageName: '',       icon: 'shirt' , useType:'product', sortOrder: 29, ageRequirement: 0, enabled: true, type:  'Retail', useGroupID: 5, weightedItem: false, expirationRequired: false, labelRequired: false, },

        {id: 25, packageType: '',taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Hookah Flavor",         itemType_Categories: categories, imageName: '',       icon: 'smoke'  , useType:'product', sortOrder: 30, ageRequirement: 18, enabled: true,     type:  'tobacco', useGroupID: 6,  weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 26,packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "E Juice",               itemType_Categories: categories, imageName: '',       icon: ''      , useType:'product', sortOrder: 31,  ageRequirement: 18, enabled: true,     type: 'tobacco',  useGroupID: 6,weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 27,packageType: '', taxable: 1,  labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "E Juice Mix",           itemType_Categories: categories, imageName: '',       icon: ''      , useType:'product', sortOrder: 32, ageRequirement: 18, enabled: true,      type:  'tobacco', useGroupID: 6, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 28,packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "E Juice Other",         itemType_Categories: categories, imageName: '',       icon: ''      , useType:'product', sortOrder: 33, ageRequirement: 18, enabled: true,      type:  'tobacco', useGroupID: 6,weightedItem: false, expirationRequired: false, labelRequired: false, },

        {id: 29,packageType: '', taxable: 1,  labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Retail",               itemType_Categories: categories, imageName: '',      icon: '', useType:'product',  sortOrder: 1, ageRequirement:0, enabled: true,           type: 'generic',  useGroupID: 11, weightedItem: true, expirationRequired: false, labelRequired: false, },

        {id: 30,packageType: 'Marijuana - Weighed',  taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Strain",                itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 2, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 31,packageType: 'Solid',                taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Edible",                itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 32,packageType: 'Solid',                taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Non Edible",            itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 33,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Packed Bud",            itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 34,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Packed Shake",          itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 35,packageType: 'Liquid',               taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Topicals",              itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 36,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Bulk Bud",              itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 37,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Strain -PCKG",          itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product',  sortOrder: 4, ageRequirement: 21, enabled: true,  type: 'cannabis', useGroupID: 7, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 60,packageType: 'Extract',              taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Extract",               itemType_Categories: categories, imageName: '',       icon: 'extract', useType:'product',  sortOrder: 39, ageRequirement: 21, enabled: true, type:  'cannabis', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 61,packageType: 'Seeds',                taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Seeds",               itemType_Categories: categories, imageName: '',       icon: 'extract', useType:'product',  sortOrder: 39, ageRequirement: 21, enabled: true, type:  'cannabis', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },

        {id: 38,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Strain",            itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 2, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 39,packageType: 'Solid',                taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Edible",            itemType_Categories: categories, imageName: '',      icon: 'brownie',useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,type: 'med-cannabis', useGroupID: 8,  weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 40,packageType: 'Solid',                taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Non Edible",        itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8,  weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 41,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Packed Bud",        itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 42,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Packed Shake",      itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 43,packageType: 'Liquid',               taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Topicals",          itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 44,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Bulk Bud",          itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 45,packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0, printLocationID: 0,prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Strain-PCKG",       itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 4, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 59,packageType: 'Med-Extract',          taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Med-Extract",               itemType_Categories: categories, imageName: '',      icon: 'extract', useType:'product',  sortOrder: 39, ageRequirement: 21, enabled: true, type:  'med-cannabis', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 62,packageType: 'Seeds',                taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Med-Seeds",               itemType_Categories: categories, imageName: '',       icon: 'extract', useType:'product',  sortOrder: 39, ageRequirement: 21, enabled: true, type:  'cannabis', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },

        {id: 46, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Alcohol",               itemType_Categories: categories, imageName: '',       icon: 'alcohol', useType:'product', sortOrder: 34, ageRequirement:  21, enabled: true, type:  'retail liquor', useGroupID: 9, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 47, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Wine",                  itemType_Categories: categories, imageName: '',       icon: 'wine'   , useType:'product', sortOrder: 35, ageRequirement:  21, enabled: true, type:  'retail liquor', useGroupID: 9, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 48, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Beer",                  itemType_Categories: categories, imageName: '',       icon: 'beer'   , useType:'product', sortOrder: 36,  ageRequirement: 21, enabled: true, type:  'retail liquor', useGroupID: 9, weightedItem: false, expirationRequired: false, labelRequired: false, },

        {id: 57, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Produce",              itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product',  sortOrder: 45 , ageRequirement: 0, enabled: true, type: 'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 49, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Produce Weighted",     itemType_Categories: categories, imageName: '',       icon: 'apple'  , useType:'product', sortOrder: 37, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10,  weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 50, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Fish Packaged",        itemType_Categories: categories, imageName: '',       icon: 'fish'   , useType:'product', sortOrder: 44, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 51, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Fish Weighted",        itemType_Categories: categories, imageName: '',       icon: 'fish'   , useType:'product', sortOrder: 43, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 52, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Meat Packaged",        itemType_Categories: categories, imageName: '',       icon: 'meat'   , useType:'product', sortOrder: 40, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 53, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Poultry Weighted",     itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product', sortOrder: 41, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 54, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Poultry Packaged",     itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product', sortOrder: 42, ageRequirement: 0, enabled: true, type:  'grocery',  useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 55, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Produce Packaged",     itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product', sortOrder: 38, ageRequirement: 0, enabled: true, type:  'grocery',  useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 56, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Meat Weighted",        itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product',  sortOrder: 39, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },

      ]
    return productType;

  }

}
