import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AuthenticationService } from '../system/authentication.service';
import { Observable  } from 'rxjs';
import { ISite }  from 'src/app/_interfaces';
import { IItemBasicB } from './menu.service';
// import { UseGroupTax, UseGroups } from './use-groups.service';

// Generated by https://quicktype.io

export interface IItemTypesList {
  id:                  number;
  name:                string;
  taxable:             number;
  type:                string;
  weightedItem:        boolean;
  expirationRequired:  boolean;
  labelRequired:       boolean;
  enabled:             boolean;
  ageRequirement:      number;
  sortOrder:           number;
  useType:             string;
  useGroupID:           number;
  itemType_Categories_List: itemType_Categories_List[];
  brandItemCount      : BrandItemCount[];
  packageType         : string;
  metrcCategoryID     : number;
  printLocationID     : number;
  printerName         : string;
  prepTicketID        : number;
  requireInStock      : boolean;
  packagingMaterial   : string;
  portionValue        : boolean;
  instructions        : string;
  enableCustomNote    : boolean;
}

export interface BrandItemCount {
  id        : number;
  name      : string;
  itemTypeID: number;
  itemCount : number;
}

export interface itemType_Categories_List {
  itemTypeName: string;
  id:           number;
  itemTypeID:   number;
  categoryID:   number;
  name:         string;
  itemCounts:   ItemCounts;
}

export interface ItemType_Categories_Reference {
  id          : number;
  itemTypeID  : number;
  categoryID  : number;
  name        : string;
  itemTypeName: string;
}

export interface itemType_Categories
{
    id          : number;
    categoryID  : number;
    itemTypeID  : number;
    itemCounts   : ItemCounts;
}

// Generated by https://quicktype.io

export interface IItemType {
  id:                  number;
  name:                string;
  taxable:             number;
  type:                string;
  weightedItem:        boolean;
  expirationRequired:  boolean;
  labelRequired:       boolean;
  ageRequirement:      number;
  sortOrder:           number;
  enabled:             boolean;
  useType:             string;
  icon:                string;
  imageName:           string;
  useGroupID:          number;
  labelTypeID:         number;
  prepTicketID:        number;
  printerName:         string;
  printLocationID:     number;
  requiresSerial:      boolean;
  packageType:         string;
  requireInStock:      boolean;
  metrcCategoryID:     number;
  instructions:        string;
  packagingMaterial:   string;
  portionValue:        string;
  itemType_Categories: ItemTypeCategory[];
  useGroups:           UseGroups;
  printerLocations:    PrinterLocations;
  enableCustomNote   : boolean;
  wicebt             : number;
}

export interface ItemTypeCategory {
  id:         number;
  itemTypeID: number;
  categoryID: number;
  itemCounts: ItemCounts;
}

export interface ItemCounts {
  id:        number;
  name:      string;
  itemCount: number;
}

export interface PrinterLocations {
  id:         number;
  name:       string;
  printer:    string;
  created:    string;
  lastEdited: string;
}

export interface UseGroups {
  id:             number;
  name:           string;
  useGroupTaxes:  UseGroupTax[];
  useGroupTaxes1: UseGroupTax[];
}

export interface UseGroupTax {
  id:         number;
  useGroupID: number;
  taxID:      number;
  taxes:      Taxes;
}

export interface Taxes {
  id:        number;
  value:     number;
  name:      string;
  taxColumn: number;
}


// Generated by https://quicktype.io

// //also in menu products service - should consolidate
// export interface IItemType {
//   id:                  number;
//   name:                string;
//   type:                string;
//   weightedItem:        boolean;
//   expirationRequired:  boolean;
//   labelRequired:       boolean;
//   ageRequirement:      number;
//   sortOrder:           number;
//   enabled:             boolean;
//   useType:             string;
//   useGroupID:          number;
//   icon:                string;
//   imageName:           string;
//   taxable:             number;
//   prepTicketID        : number;
//   labelTypeID         : number;
//   printerName         : string;
//   printLocationID     : number;
//   itemType_Categories : ItemTypeCategory[];
//   requiresSerial      : boolean;
//   packageType         : string;
//   requireInStock      : boolean;
//   metrcCategoryID     : number;
//   prepTicketID       : number;
//   packagingMaterial   : string;
//   portionValue        : boolean;
//   instructions        : string;
// }

export interface FlatRateTax {
  id:                number;
  name:              string;
  flatRateTaxValues: FlatRateTaxValue[];
}

export interface FlatRateTaxValue {
  id:            number;
  flatRateTaxID: number;
  rateStart:     number;
  rateEnd:       number;
  fee:           number;
}

// export interface ItemTypeCategory {
//   id:         number;
//   categoryID: number;
//   itemTypeID: number;
//   itemCounts : ItemCounts;
// }

export interface ItemCounts {
  id       : number;
  name     : string; //"sample string 2",
  itemCount: number;
}

export interface Tax {
  id:     number;
  amount: number;
  name:   string;
}

@Injectable({
  providedIn: 'root'
})
export class ItemTypeService {

packageType = ['Not-Specified', 'Marijuana Weighed',
               'Marijuana - Packaged', 'Medicine - Weighed', 'Medicine Each', 'Seeds', 'Plants', 'Concentrates', 'Solid', 'Liquid', 'Extract']
type       = [
   'grouping',
   'restaurant',
   'discounts',
   'tobacco',
   'cannabis',
   'retail',
   'med-cannabis',
   'grocery',
   'retail liquor',
   'service liquor'
  ]
useType = ['product', 'adjustment', 'category']

site: ISite;
constructor(private http: HttpClient,
            private auth: AuthenticationService) { }


  delete(site: ISite, id: number): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${id}`;

    const endPoint = 'deleteItemType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.delete<IItemType>(url);

  }

  deleteItems(site: ISite, items: IItemType[]): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = ``;

    const endPoint = 'DeleteItemTypes';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.post<IItemType[]>(url, items);

  }


  initItemTypes(site: ISite, iItemType: IItemType[]): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = '';

    const endPoint ='postItemTypeList';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.post<IItemType[]>(url, iItemType);

  }


  getBasicTypes(site: ISite): Observable<IItemBasicB[]> {

    const controller = '/ItemTypes/';

    const parameters = '';

    const endPoint = 'GetBasicTypes';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemBasicB[]>(url);

  }

  getItemTypes(site: ISite): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = '';

    const endPoint = 'GetItemTypes';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemType[]>(url);

  }

  getItemTypesByType(site: ISite, type: string): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = `?type=${type}`;

    const endPoint = 'GetItemTypesByType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemType[]>(url);

  }

  getItemTypesByUseType(site: ISite, useType: string): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = `?useType=${useType}`;

    const endPoint = 'GetItemTypesByUseType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemType[]>(url);

  }


  getItemTypeCategoriesReadOnlyList(site: ISite): Observable<IItemTypesList[]> {

    const controller = '/ItemTypes/';

    const parameters = ``;

    const endPoint = 'GetItemTypeCategoriesReadOnlyList';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemTypesList[]>(url);

  }

  getBasicTypesByUseType(site: ISite, useType: string): Observable<any[]> {

    const controller = '/ItemTypes/';

    const parameters = `?useType=${useType}`;

    const endPoint = 'getBasicTypesByUseType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<any[]>(url);

  }



  getItemType(site: ISite, id: number): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${id}`;

    const endPoint = 'getItemType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<IItemType>(url);

  }


  getItemTypeCategories(site: ISite, id: number): Observable<ItemType_Categories_Reference[]> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${id}`;

    const endPoint = 'getItemTypeCategories';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<ItemType_Categories_Reference[]>(url);

  }


  getItemTypeCategoriesAll(site: ISite): Observable<ItemType_Categories_Reference[]> {

    const controller = '/ItemTypes/';

    const parameters = ``;

    const endPoint = 'getItemTypeCategoriesAll';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.get<ItemType_Categories_Reference[]>(url);

  }

  putItemTypesList(site: ISite, iItemType: IItemType[]): Observable<IItemType[]> {

    const controller = '/ItemTypes/';

    const parameters = '';

    const endPoint = 'putItemTypeList';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.put<IItemType[]>(url, iItemType);

  }

  putItemType(site: ISite, itemType: IItemType): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${itemType.id}`;

    const endPoint = 'putItemType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;
    console.log(url)
    return  this.http.put<IItemType>(url, itemType);

  }

  postItemType(site: ISite, itemType: IItemType): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = ``;

    const endPoint = 'PostItemType';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.post<IItemType>(url, itemType);

  }

  saveItemType(site: ISite, itemType: IItemType): Observable<IItemType> {

      if ( !itemType.id || itemType.id == 0) {
        return  this.postItemType(site, itemType)
      }
      if (itemType.id != 0) {
        return  this.putItemType(site, itemType)
      }

  }


  putItemTypeNoChildren(site: ISite, itemType: IItemType): Observable<IItemType> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${itemType.id}`;

    const endPoint = 'putItemTypeNoChildren';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.put<IItemType>(url, itemType);

  }


  saveCategories(site: ISite, id: number, categories: itemType_Categories[]): Observable<itemType_Categories[]> {

    const controller = '/ItemTypes/';

    const parameters = `?id=${id}`;

    const endPoint = 'saveCategories';

    const url = `${site.url}${controller}${endPoint}${parameters}`;

    return  this.http.post<itemType_Categories[]>(url, categories);

  }



  getDefaultItemTypes(): IItemType[]  {


    const groupsTaxes  = {} as UseGroupTax[]
    let   productType  = {} as IItemType[]
    let   useGroup     = {useGroupTaxes: groupsTaxes } as UseGroups
    let   useGroups    = [useGroup] as UseGroups[]

    const tax          = {} as Tax
    const flatRateTax  = {} as FlatRateTax
    const categories   = {} as itemType_Categories[];
    const itemcounts   = {} as ItemCounts
    const printerLocations = {} as PrinterLocations;
        // ;4;Category;5;Sub Category;6;Department;

    productType =
      [
        {id: 1,
        labelTypeID: 0,
        prepTicketID: 0,
        printLocationID: 0,
        printerName: '',
        name : "Generic",
        taxable            : 1,
        type               : 'generic',
        weightedItem       : false,
        expirationRequired : false,
        labelRequired      : false,
        enabled            : true,
        ageRequirement     : 0,
        sortOrder          : 1,
        useType            : 'generic',
        icon               : 'generic',
        useGroupID         : 11,
        imageName          : '',
        requiresSerial     : false,
        packageType        : '',
        requireInStock     : false,
        metrcCategoryID    : 0,
        packagingMaterial  : '',
        portionValue       : '',
        instructions       : '',
        itemType_Categories: categories,
        useGroups          : useGroup,
        printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
      },

        {id: 2,   portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '',  taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0, requiresSerial: false, printerName: '',    name : "Modifier",              itemType_Categories: categories, imageName: '',       icon: 'food', useType:'product', sortOrder: 11, ageRequirement: 0,   enabled: true,     type: 'restaurant', useGroupID: 1, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 3,   portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',    name : "Text",                  itemType_Categories: categories, imageName: '',       icon: 'food', useType:'adjustment', sortOrder: 12, ageRequirement: 0, enabled: true,     type: 'restaurant', useGroupID: 1, weightedItem: true, expirationRequired: false, labelRequired: false, },

        {id: 4, portionValue       : '',
                packagingMaterial: '',
                useGroups          : useGroup,
                printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                instructions        : '',metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Category",              itemType_Categories: categories, imageName: '',       icon: 'category',useType:'category', sortOrder: 8, ageRequirement: 0, enabled: true,    type: 'grouping', useGroupID: 3, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 5, portionValue       : '',
                packagingMaterial: '',
                useGroups          : useGroup,
                printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '',  taxable: 0,  labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Sub Category",          itemType_Categories: categories, imageName: '',       icon: 'group'  , useType:'category', sortOrder: 9, ageRequirement: 0, enabled: true,    type: 'grouping', useGroupID: 3,weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 6, portionValue       : '',
                packagingMaterial: '',
                useGroups          : useGroup,
                printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '',  taxable: 0,  labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Department",            itemType_Categories: categories, imageName: '',       icon: 'department',useType:'category', sortOrder: 10, ageRequirement: 0, enabled: true, type: 'grouping', useGroupID: 3,weightedItem: true, expirationRequired: false, labelRequired: false, },

        {id: 8,   portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Discount % Entire Order",itemType_Categories: categories, imageName: '',      icon: 'coupon',useType:'adjustment', sortOrder: 13, ageRequirement: 0, enabled: true,  type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 7,   portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Cash Discount on Order", itemType_Categories: categories, imageName: '',      icon: 'coupon',useType:'adjustment', sortOrder: 14, ageRequirement: 0, enabled: true,  type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 9,   portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '',  taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Quantity Off Item",     itemType_Categories: categories, imageName: '',       icon: 'coupon',useType:'adjustment', sortOrder: 15, ageRequirement: 0, enabled: true,  type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 10,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '',taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Price Level 1",         itemType_Categories: categories, imageName: '',       icon: ''      ,useType:'adjustment', sortOrder: 16, ageRequirement: 0, enabled: true,  type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 11,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Price Level 2",         itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 17, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 12,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0,prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Price Level 3",         itemType_Categories: categories, imageName: '',        icon: ''      , useType:'adjustment', sortOrder: 18, ageRequirement: 0, enabled: true, type:  'discounts',  useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 13,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Discount % One Item",   itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 19, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 15,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Promo Unspecified",     itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 20, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 14,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Blind Item",            itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 21, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 16,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Point Adjustment",      itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 22, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 17,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0, requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Adjust Total ",         itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 23, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 18,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Cash Discount on Item", itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 24, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 19,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Gift Card",             itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 25,ageRequirement: 0,  enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 20,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "Tare Value",            itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 27, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 21,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Gift Card Mercury",     itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment', sortOrder: 26, ageRequirement: 0, enabled: true, type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 22,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Gratuity",              itemType_Categories: categories, imageName: '',       icon: ''      , useType:'adjustment',  sortOrder: 28,  ageRequirement: 0, enabled:true,type:  'discounts', useGroupID: 2, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 23,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '',taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Matrix Item",           itemType_Categories: categories, imageName: '',       icon: 'matrix',useType:'product',  sortOrder: 29, ageRequirement: 0, enabled: true, type:  'Retail', useGroupID: 5, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 24,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Retail Clothing",       itemType_Categories: categories, imageName: '',       icon: 'shirt' , useType:'product', sortOrder: 29, ageRequirement: 0, enabled: true, type:  'Retail', useGroupID: 5, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 25,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,   requireInStock: false, packageType: '',taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Hookah Flavor",         itemType_Categories: categories, imageName: '',       icon: 'smoke'  , useType:'product', sortOrder: 30, ageRequirement: 18, enabled: true,     type:  'tobacco', useGroupID: 6,  weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 26,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "E Juice",               itemType_Categories: categories, imageName: '',       icon: ''      , useType:'product', sortOrder: 31,  ageRequirement: 18, enabled: true,     type: 'tobacco',  useGroupID: 6,weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 27,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 1,  labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',  name : "E Juice Mix",           itemType_Categories: categories, imageName: '',       icon: ''      , useType:'product', sortOrder: 32, ageRequirement: 18, enabled: true,      type:  'tobacco', useGroupID: 6, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 28,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "E Juice Other",         itemType_Categories: categories, imageName: '',       icon: ''      , useType:'product', sortOrder: 33, ageRequirement: 18, enabled: true,      type:  'tobacco', useGroupID: 6,weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 29,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 1,  labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Retail",               itemType_Categories: categories, imageName: '',      icon: '', useType:'product',  sortOrder: 1, ageRequirement:0, enabled: true,           type: 'generic',  useGroupID: 11, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 30,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Marijuana - Weighed',  taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Strain",                itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 2, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 31,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Solid',                taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Edible",                itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 32,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Solid',                taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Non Edible",            itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 33,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Packed Bud",            itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 34,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Packed Shake",          itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 35,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Liquid',               taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Topicals",              itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 36,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Bulk Bud",              itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,   type: 'cannabis', useGroupID: 7, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 37,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Strain -PCKG",          itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product',  sortOrder: 4, ageRequirement: 21, enabled: true,  type: 'cannabis', useGroupID: 7, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 60,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Extract',              taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Extract",               itemType_Categories: categories, imageName: '',       icon: 'extract', useType:'product',  sortOrder: 39, ageRequirement: 21, enabled: true, type:  'cannabis', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 61,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Seeds',                taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Seeds",               itemType_Categories: categories, imageName: '',       icon: 'extract', useType:'product',  sortOrder: 39, ageRequirement: 21, enabled: true, type:  'cannabis', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },

        {id: 38,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Strain",            itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 2, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 39,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',   metrcCategoryID : 0,  requireInStock: false, packageType: 'Solid',                taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Edible",            itemType_Categories: categories, imageName: '',      icon: 'brownie',useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true,type: 'med-cannabis', useGroupID: 8,  weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 40,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Solid',                taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Non Edible",        itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8,  weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 41,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Packed Bud",        itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 42,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Packed Shake",      itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 43,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0, requireInStock: false, packageType: 'Liquid',               taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Topicals",          itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 44,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Bulk Bud",          itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 3, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 45,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Marijuana - Packaged', taxable: 1, labelTypeID: 0, printLocationID: 0,prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Med-Strain-PCKG",       itemType_Categories: categories, imageName: '',      icon: 'flower', useType:'product', sortOrder: 4, ageRequirement: 21, enabled: true, type: 'med-cannabis', useGroupID: 8, weightedItem: true, expirationRequired: false, labelRequired: false, },
        {id: 59,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Med-Extract',          taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Med-Extract",               itemType_Categories: categories, imageName: '',      icon: 'extract', useType:'product',  sortOrder: 39, ageRequirement: 21, enabled: true, type:  'med-cannabis', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 62,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,  requireInStock: false, packageType: 'Seeds',                taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false,printerName: '',   name : "Med-Seeds",               itemType_Categories: categories, imageName: '',       icon: 'extract', useType:'product',  sortOrder: 39, ageRequirement: 21, enabled: true, type:  'cannabis', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 46,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',   metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Alcohol",               itemType_Categories: categories, imageName: '',       icon: 'alcohol', useType:'product', sortOrder: 34, ageRequirement:  21, enabled: true, type:  'retail liquor', useGroupID: 9, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 47,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Wine",                  itemType_Categories: categories, imageName: '',       icon: 'wine'   , useType:'product', sortOrder: 35, ageRequirement:  21, enabled: true, type:  'retail liquor', useGroupID: 9, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 48,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',     metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 1, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Beer",                  itemType_Categories: categories, imageName: '',       icon: 'beer'   , useType:'product', sortOrder: 36,  ageRequirement: 21, enabled: true, type:  'retail liquor', useGroupID: 9, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 57,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Produce",              itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product',  sortOrder: 45 , ageRequirement: 0, enabled: true, type: 'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 49,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Produce Weighted",     itemType_Categories: categories, imageName: '',       icon: 'apple'  , useType:'product', sortOrder: 37, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10,  weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 50,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Fish Packaged",        itemType_Categories: categories, imageName: '',       icon: 'fish'   , useType:'product', sortOrder: 44, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 51,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',
                  metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Fish Weighted",        itemType_Categories: categories, imageName: '',       icon: 'fish'   , useType:'product', sortOrder: 43, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 52,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '',  metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Meat Packaged",        itemType_Categories: categories, imageName: '',       icon: 'meat'   , useType:'product', sortOrder: 40, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 53,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Poultry Weighted",     itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product', sortOrder: 41, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 54,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Poultry Packaged",     itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product', sortOrder: 42, ageRequirement: 0, enabled: true, type:  'grocery',  useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 55,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,   requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',  name : "Produce Packaged",     itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product', sortOrder: 38, ageRequirement: 0, enabled: true, type:  'grocery',  useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
        {id: 56,  portionValue       : '',
                  packagingMaterial: '',
                  useGroups          : useGroup,
                  printerLocations   : printerLocations, enableCustomNote: false, wicebt: 0,
                  instructions        : '', metrcCategoryID : 0,  requireInStock: false, packageType: '', taxable: 0, labelTypeID: 0,printLocationID: 0, prepTicketID: 0,  requiresSerial: false, printerName: '',   name : "Meat Weighted",        itemType_Categories: categories, imageName: '',       icon: 'chicken', useType:'product',  sortOrder: 39, ageRequirement: 0, enabled: true, type:  'grocery', useGroupID: 10, weightedItem: false, expirationRequired: false, labelRequired: false, },
      ]
    return productType;

  }

}
