// Generated by https://quicktype.io

export interface METRCItems {
  Id:                                  number;
  Name:                                string;
  ProductCategoryName:                 string;
  ProductCategoryType:                 string;
  QuantityType:                        string;
  DefaultLabTestingState:              string;
  UnitOfMeasureName:                   string;
  ApprovalStatus:                      string;
  ApprovalStatusDateTime:              string;
  StrainId:                            number;
  StrainName:                          string;
  AdministrationMethod:                null;
  UnitCbdPercent:                      null;
  UnitCbdContent:                      null;
  UnitCbdContentUnitOfMeasureName:     null;
  UnitCbdContentDose:                  null;
  UnitCbdContentDoseUnitOfMeasureName: null;
  UnitThcPercent:                      null;
  UnitThcContent:                      null;
  UnitThcContentUnitOfMeasureName:     null;
  UnitThcContentDose:                  null;
  UnitThcContentDoseUnitOfMeasureName: null;
  UnitVolume:                          null;
  UnitVolumeUnitOfMeasureName:         null;
  UnitWeight:                          null;
  UnitWeightUnitOfMeasureName:         null;
  ServingSize:                         null;
  SupplyDurationDays:                  null;
  NumberOfDoses:                       null;
  UnitQuantity:                        null;
  UnitQuantityUnitOfMeasureName:       null;
  Ingredients:                         null;
  Description:                         null;
  IsUsed:                              boolean;
}

export interface METRCItemsCategories {
  id:                           number;
  name:                         string;
  productCategoryType:          string;
  quantityType:                 string;
  requiresStrain:               boolean;
  requiresItemBrand:            boolean;
  requiresAdministrationMethod: boolean;
  requiresUnitCbdPercent:       boolean;
  requiresUnitCbdContent:       boolean;
  requiresUnitCbdContentDose:   boolean;
  requiresUnitThcPercent:       boolean;
  requiresUnitThcContent:       boolean;
  requiresUnitThcContentDose:   boolean;
  requiresUnitVolume:           boolean;
  requiresUnitWeight:           boolean;
  requiresServingSize:          boolean;
  requiresSupplyDurationDays:   boolean;
  requiresNumberOfDoses:        boolean;
  requiresIngredients:          boolean;
  requiresDescription:          boolean;
  requiresProductPhotos:        boolean;
  requiresLabelPhotos:          boolean;
  requiresPackagingPhotos:      boolean;
  canContainSeeds:              boolean;
  canBeRemediated:              boolean;
  lastModified:                 string;
}

// Generated by https://quicktype.io

export interface MetrcItemsBrands {
  Name:   string;
  Status: string;
}

// Generated by https://quicktype.io

export interface METRCItemsCreate {
  ItemCategory:                    string;
  Name:                            string;
  UnitOfMeasure:                   string;
  Strain:                          null | string;
  ItemBrand:                       null;
  AdministrationMethod:            null;
  UnitCbdPercent:                  null;
  UnitCbdContent:                  null;
  UnitCbdContentUnitOfMeasure:     null;
  UnitCbdContentDose:              null;
  UnitCbdContentDoseUnitOfMeasure: null;
  UnitThcPercent:                  null;
  UnitThcContent:                  number | null;
  UnitThcContentUnitOfMeasure:     null | string;
  UnitThcContentDose:              number | null;
  UnitThcContentDoseUnitOfMeasure: null | string;
  UnitVolume:                      number | null;
  UnitVolumeUnitOfMeasure:         null | string;
  UnitWeight:                      number | null;
  UnitWeightUnitOfMeasure:         null | string;
  ServingSize:                     null;
  SupplyDurationDays:              null;
  NumberOfDoses:                   number | null;
  Ingredients:                     null;
  Description:                     null;
}

// Generated by https://quicktype.io

export interface METRCItemsUpdate {
  Id:                              number;
  Name:                            string;
  ItemCategory:                    string;
  UnitOfMeasure:                   string;
  Strain:                          null | string;
  ItemBrand:                       null;
  AdministrationMethod:            null;
  UnitCbdPercent:                  null;
  UnitCbdContent:                  null;
  UnitCbdContentUnitOfMeasure:     null;
  UnitCbdContentDose:              null;
  UnitCbdContentDoseUnitOfMeasure: null;
  UnitThcPercent:                  null;
  UnitThcContent:                  number | null;
  UnitThcContentUnitOfMeasure:     null | string;
  UnitThcContentDose:              number | null;
  UnitThcContentDoseUnitOfMeasure: null | string;
  UnitVolume:                      number | null;
  UnitVolumeUnitOfMeasure:         null | string;
  UnitWeight:                      number | null;
  UnitWeightUnitOfMeasure:         null | string;
  ServingSize:                     null;
  SupplyDurationDays:              null;
  NumberOfDoses:                   number | null;
  Ingredients:                     null;
  Description:                     null;
}
