// Generated by https://quicktype.io
export interface METRCLabTestsStates {}

// Generated by https://quicktype.io

export interface METRCLabTestTypes {
  Id:                   number;
  Name:                 string;
  RequiresTestResult:   boolean;
  InformationalOnly:    boolean;
  AlwaysPasses:         boolean;
  LabTestResultMode:    number;
  LabTestResultMinimum: null;
  LabTestResultMaximum: null;
  DependencyMode:       number | string;
}

// Generated by https://quicktype.io

export interface METRCLabTestsResults {
  PackageId:                number;
  LabTestResultId:          number;
  LabFacilityLicenseNumber: string;
  LabFacilityName:          string;
  SourcePackageLabel:       string;
  ProductName:              string;
  ProductCategoryName:      string;
  TestPerformedDate:        string;
  OverallPassed:            boolean;
  RevokedDate:              null;
  ResultReleased:           boolean;
  ResultReleaseDateTime:    null | string;
  TestTypeName:             string;
  TestPassed:               boolean;
  TestResultLevel:          number;
  TestComment:              string;
  TestInformationalOnly:    boolean;
  LabTestDetailRevokedDate: null;
}

// Generated by https://quicktype.io

export interface METRCLabTestsRecordPOST {
  Label:              string;
  ResultDate:         string;
  DocumentFileName:   null | string;
  DocumentFileBase64: null | string;
  Results:            Result[];
}

export interface Result {
  LabTestTypeName: string;
  Quantity:        number;
  Passed:          boolean;
  Notes:           string;
}

// Generated by https://quicktype.io

export interface METRCLabTEstsLabeTestDocument {
  LabTestResultId:    number;
  DocumentFileName:   string;
  DocumentFileBase64: string;
}

// Generated by https://quicktype.io

export interface METRCLabTestResultsRelease {
  PackageLabel: string;
}
