// Generated by https://quicktype.io

export interface METRCPatientsGet {
  PatientId:                   number;
  LicenseNumber:               string;
  RegistrationDate:            string;
  LicenseEffectiveStartDate:   string;
  LicenseEffectiveEndDate:     string;
  RecommendedPlants:           number;
  RecommendedSmokableQuantity: number;
  HasSalesLimitExemption:      boolean;
  OtherFacilitiesCount:        number;
}

// Generated by https://quicktype.io

export interface METRCPatientsAdd {
  LicenseNumber:               string;
  LicenseEffectiveStartDate:   string;
  LicenseEffectiveEndDate:     string;
  RecommendedPlants:           number;
  RecommendedSmokableQuantity: number;
  HasSalesLimitExemption:      boolean;
  ActualDate:                  string;
}

// Generated by https://quicktype.io

export interface METRCPatientsUpdate {
  LicenseNumber:               string;
  NewLicenseNumber:            null | string;
  LicenseEffectiveStartDate:   string;
  LicenseEffectiveEndDate:     string;
  RecommendedPlants:           number;
  RecommendedSmokableQuantity: number;
  HasSalesLimitExemption:      boolean;
  ActualDate:                  string;
}

