// Generated by https://quicktype.io

export interface METRCPlantBatchesGET {
  Id:                   number;
  Name:                 string;
  Type:                 string;
  LocationId:           null;
  LocationName:         null;
  LocationTypeName:     null;
  StrainId:             number;
  StrainName:           string;
  PatientLicenseNumber: null;
  UntrackedCount:       number;
  TrackedCount:         number;
  PackagedCount:        number;
  HarvestedCount:       number;
  DestroyedCount:       number;
  SourcePackageId:      null;
  SourcePackageLabel:   null;
  SourcePlantId:        null;
  SourcePlantLabel:     null;
  SourcePlantBatchId:   null;
  SourcePlantBatchName: null;
  PlantedDate:          string;
  LastModified:         string;
}

export interface METRCPlantBatchesTypesGET {}

// Generated by https://quicktype.io

export interface METRCPlantBatchesCreatePlantingsPOST {
  Name:                 string;
  Type:                 string;
  Count:                number;
  Strain:               string;
  Location:             null;
  PatientLicenseNumber: string;
  ActualDate:           string;
}

// Generated by https://quicktype.io

export interface METRCPlantBatchesCreatePackagesPOST {
  Id:                   number | null;
  PlantBatch:           null | string;
  Count:                number;
  Location:             null;
  Item:                 string;
  Tag:                  string;
  PatientLicenseNumber: string;
  Note:                 string;
  IsTradeSample:        boolean;
  IsDonation:           boolean;
  ActualDate:           string;
}


// Generated by https://quicktype.io

export interface METRCPlantBatchesSplitPOST {
  PlantBatch:           string;
  GroupName:            string;
  Type:                 string;
  Count:                number;
  Location:             null;
  Strain:               string;
  PatientLicenseNumber: null | string;
  ActualDate:           string;
}

// Generated by https://quicktype.io

export interface METRCPlantBatchsCreatePackagesFromMOtherPlantPOST {
  Id:                   number | null;
  PlantBatch:           null | string;
  Count:                number;
  Location:             null;
  Item:                 string;
  Tag:                  string;
  PatientLicenseNumber: string;
  Note:                 string;
  IsTradeSample:        boolean;
  IsDonation:           boolean;
  ActualDate:           string;
}

// Generated by https://quicktype.io

export interface METRCPlantBatchesChangeGrowthPhasePOST {
  Name:                 string;
  Count:                number;
  StartingTag:          string;
  GrowthPhase:          string;
  NewLocation:          string;
  GrowthDate:           string;
  PatientLicenseNumber: string;
}

// Generated by https://quicktype.io

export interface METRCPlantBatchesMovePlanBatchesPUT {
  Name:     string;
  Location: string;
  MoveDate: string;
}

// Generated by https://quicktype.io

export interface METRCPLantBatchesAdditivesPOST {
  AdditiveType:             string;
  ProductTradeName:         string;
  EpaRegistrationNumber:    null;
  ProductSupplier:          string;
  ApplicationDevice:        string;
  TotalAmountApplied:       number;
  TotalAmountUnitOfMeasure: string;
  ActiveIngredients:        ActiveIngredient[];
  PlantBatchName:           string;
  ActualDate:               string;
}

export interface ActiveIngredient {
  Name:       string;
  Percentage: number;
}

// Generated by https://quicktype.io

export interface METRCPlantBatchesDestroyPOST {
  PlantBatch: string;
  Count:      number;
  ReasonNote: string;
  ActualDate: string;
}
