
export interface METRCPlantsGet {
  Id:                                number;
  Label:                             string;
  State:                             string;
  GrowthPhase:                       string;
  PlantBatchId:                      number;
  PlantBatchName:                    string;
  PlantBatchTypeName:                string;
  StrainId:                          number;
  StrainName:                        string;
  LocationId:                        number;
  LocationName:                      string;
  LocationTypeName:                  null;
  PatientLicenseNumber:              null;
  HarvestId:                         null;
  HarvestedUnitOfWeightName:         null;
  HarvestedUnitOfWeightAbbreviation: null;
  HarvestedWetWeight:                null;
  HarvestCount:                      number;
  IsOnHold:                          boolean;
  PlantedDate:                       string;
  VegetativeDate:                    string;
  FloweringDate:                     null;
  HarvestedDate:                     null;
  DestroyedDate:                     null;
  DestroyedNote:                     null;
  DestroyedByUserName:               null;
  LastModified:                      string;
}

export interface METRCPlantsAdditivesGet {
  AdditiveTypeName:      null;
  ProductTradeName:      string;
  EpaRegistrationNumber: null;
  ProductSupplier:       string;
  ApplicationDevice:     string;
  AmountUnitOfMeasure:   string;
  TotalAmountApplied:    number;
  PlantBatchId:          null;
  PlantBatchName:        null;
  PlantCount:            number;
}

export interface METRCPlantsGrowthPhasesGET {}
export interface METRCPlantsAdditivesTypesGET {}
export interface METRCPlantsWasteMethodsGET {}

export interface METRCPlantsWasteReasonsGet {
  Name:         string;
  RequiresNote: boolean;
}


export interface METRCPlantsMovePlantsPOST {
  Id:         number | null;
  Label:      null | string;
  Location:   string;
  ActualDate: string;
}


export interface METRCPlantsChangeGrowthPhasesPOST {
  Id:          number | null;
  Label:       null | string;
  NewTag:      string;
  GrowthPhase: string;
  NewLocation: string;
  GrowthDate:  string;
}

export interface METRCPOSTPlantsDestroyPlantsPOST {
  Id:                     number | null;
  Label:                  null | string;
  WasteMethodName:        string;
  WasteMaterialMixed:     string;
  WasteWeight:            number;
  WasteUnitOfMeasureName: string;
  WasteReasonName:        string;
  ReasonNote:             string;
  ActualDate:             string;
}


// Generated by https://quicktype.io

export interface METRCPlantsAdditivesPOST {
  AdditiveType:             string;
  ProductTradeName:         string;
  EpaRegistrationNumber:    null;
  ProductSupplier:          string;
  ApplicationDevice:        string;
  TotalAmountApplied:       number;
  TotalAmountUnitOfMeasure: string;
  ActiveIngredients:        ActiveIngredient[];
  PlantLabels:              string[];
  ActualDate:               string;
}

export interface ActiveIngredient {
  Name:       string;
  Percentage: number;
}

// Generated by https://quicktype.io

export interface METRCPlantsAdditivesByLocationPOST {
  AdditiveType:             string;
  ProductTradeName:         string;
  EpaRegistrationNumber:    null;
  ProductSupplier:          string;
  ApplicationDevice:        string;
  TotalAmountApplied:       number;
  TotalAmountUnitOfMeasure: string;
  ActiveIngredients:        ActiveIngredient[];
  LocationName:             string;
  ActualDate:               string;
}

export interface ActiveIngredient {
  Name:       string;
  Percentage: number;
}

// Generated by https://quicktype.io

export interface METRCPlantsCreatePlantingsPOST {
  PlantLabel:           string;
  PlantBatchName:       string;
  PlantBatchType:       string;
  PlantCount:           number;
  LocationName:         null;
  StrainName:           string;
  PatientLicenseNumber: string;
  ActualDate:           string;
}


export interface METRCPlantsCreatePlantBatchPackagePOST {
  PlantLabel:           string;
  PackageTag:           string;
  PlantBatchType:       string;
  Item:                 string;
  Location:             null | string;
  Note:                 null;
  IsTradeSample:        boolean;
  PatientLicenseNumber: null;
  IsDonation:           boolean;
  Count:                number;
  ActualDate:           string;
}

export interface METRCPlantsManicurePlantPOST {
  Plant:                string;
  Weight:               number;
  UnitOfWeight:         string;
  DryingLocation:       string;
  HarvestName:          null | string;
  PatientLicenseNumber: string;
  ActualDate:           string;
}

export interface METRCPlantsHarvestPlantsPOST {
  Plant:                string;
  Weight:               number;
  UnitOfWeight:         string;
  DryingLocation:       string;
  HarvestName:          null | string;
  PatientLicenseNumber: string;
  ActualDate:           string;
}
