// Generated by https://quicktype.io

export interface METRCStrainsGet {
  Id:               number;
  Name:             string;
  TestingStatus:    string;
  ThcLevel:         null;
  CbdLevel:         null;
  IndicaPercentage: number;
  SativaPercentage: number;
  IsUsed:           boolean;
  Genetics:         string;
}

// Generated by https://quicktype.io

export interface MetrcStrainsCreate {
  Name:             string;
  TestingStatus:    string;
  ThcLevel:         number;
  CbdLevel:         number;
  IndicaPercentage: number;
  SativaPercentage: number;
}

// Generated by https://quicktype.io

export interface METRCStrainsUpdate {
  Id:               number;
  Name:             string;
  TestingStatus:    string;
  ThcLevel:         number;
  CbdLevel:         number;
  IndicaPercentage: number;
  SativaPercentage: number;
}
