// Generated by https://quicktype.io

export interface METRCTransfersIncomingGET {
  Id:                                 number;
  ManifestNumber:                     string;
  ShipmentLicenseType:                number;
  ShipperFacilityLicenseNumber:       string;
  ShipperFacilityName:                string;
  Name:                               null;
  TransporterFacilityLicenseNumber:   string;
  TransporterFacilityName:            string;
  DriverName:                         string;
  DriverOccupationalLicenseNumber:    string;
  DriverVehicleLicenseNumber:         string;
  VehicleMake:                        string;
  VehicleModel:                       string;
  VehicleLicensePlateNumber:          string;
  DeliveryCount:                      number;
  ReceivedDeliveryCount:              number;
  PackageCount:                       number;
  ReceivedPackageCount:               number;
  ContainsPlantPackage:               boolean;
  ContainsProductPackage:             boolean;
  ContainsTradeSample:                boolean;
  ContainsDonation:                   boolean;
  ContainsTestingSample:              boolean;
  ContainsProductRequiresRemediation: boolean;
  ContainsRemediatedProductPackage:   boolean;
  CreatedDateTime:                    string;
  CreatedByUserName:                  null;
  LastModified:                       string;
  DeliveryId:                         number;
  RecipientFacilityLicenseNumber:     string;
  RecipientFacilityName:              string;
  ShipmentTypeName:                   string;
  ShipmentTransactionType:            string;
  EstimatedDepartureDateTime:         string;
  ActualDepartureDateTime:            null;
  EstimatedArrivalDateTime:           string;
  ActualArrivalDateTime:              null;
  DeliveryPackageCount:               number;
  DeliveryReceivedPackageCount:       number;
  ReceivedDateTime:                   string;
  EstimatedReturnDepartureDateTime:   null;
  ActualReturnDepartureDateTime:      null;
  EstimatedReturnArrivalDateTime:     null;
  ActualReturnArrivalDateTime:        null;
}

// Generated by https://quicktype.io

export interface METRCTransfersOutgoingGet {
  Id:                                 number;
  ManifestNumber:                     string;
  ShipmentLicenseType:                number;
  ShipperFacilityLicenseNumber:       string;
  ShipperFacilityName:                string;
  Name:                               null;
  TransporterFacilityLicenseNumber:   string;
  TransporterFacilityName:            string;
  DriverName:                         string;
  DriverOccupationalLicenseNumber:    string;
  DriverVehicleLicenseNumber:         string;
  VehicleMake:                        string;
  VehicleModel:                       string;
  VehicleLicensePlateNumber:          string;
  DeliveryCount:                      number;
  ReceivedDeliveryCount:              number;
  PackageCount:                       number;
  ReceivedPackageCount:               number;
  ContainsPlantPackage:               boolean;
  ContainsProductPackage:             boolean;
  ContainsTradeSample:                boolean;
  ContainsDonation:                   boolean;
  ContainsTestingSample:              boolean;
  ContainsProductRequiresRemediation: boolean;
  ContainsRemediatedProductPackage:   boolean;
  CreatedDateTime:                    string;
  CreatedByUserName:                  null;
  LastModified:                       string;
  DeliveryId:                         number;
  RecipientFacilityLicenseNumber:     null;
  RecipientFacilityName:              null;
  ShipmentTypeName:                   null;
  ShipmentTransactionType:            null;
  EstimatedDepartureDateTime:         string;
  ActualDepartureDateTime:            null;
  EstimatedArrivalDateTime:           string;
  ActualArrivalDateTime:              null;
  DeliveryPackageCount:               number;
  DeliveryReceivedPackageCount:       number;
  ReceivedDateTime:                   null;
  EstimatedReturnDepartureDateTime:   null;
  ActualReturnDepartureDateTime:      null;
  EstimatedReturnArrivalDateTime:     null;
  ActualReturnArrivalDateTime:        null;
}

// Generated by https://quicktype.io

export interface METRCTransfersRejectedGet {
  Id:                                 number;
  ManifestNumber:                     string;
  ShipmentLicenseType:                number;
  ShipperFacilityLicenseNumber:       string;
  ShipperFacilityName:                string;
  Name:                               null;
  TransporterFacilityLicenseNumber:   string;
  TransporterFacilityName:            string;
  DriverName:                         string;
  DriverOccupationalLicenseNumber:    string;
  DriverVehicleLicenseNumber:         string;
  VehicleMake:                        string;
  VehicleModel:                       string;
  VehicleLicensePlateNumber:          string;
  DeliveryCount:                      number;
  ReceivedDeliveryCount:              number;
  PackageCount:                       number;
  ReceivedPackageCount:               number;
  ContainsPlantPackage:               boolean;
  ContainsProductPackage:             boolean;
  ContainsTradeSample:                boolean;
  ContainsDonation:                   boolean;
  ContainsTestingSample:              boolean;
  ContainsProductRequiresRemediation: boolean;
  ContainsRemediatedProductPackage:   boolean;
  CreatedDateTime:                    string;
  CreatedByUserName:                  null;
  LastModified:                       string;
  DeliveryId:                         number;
  RecipientFacilityLicenseNumber:     string;
  RecipientFacilityName:              string;
  ShipmentTypeName:                   string;
  ShipmentTransactionType:            string;
  EstimatedDepartureDateTime:         string;
  ActualDepartureDateTime:            null;
  EstimatedArrivalDateTime:           string;
  ActualArrivalDateTime:              null;
  DeliveryPackageCount:               number;
  DeliveryReceivedPackageCount:       number;
  ReceivedDateTime:                   string;
  EstimatedReturnDepartureDateTime:   null;
  ActualReturnDepartureDateTime:      null;
  EstimatedReturnArrivalDateTime:     null;
  ActualReturnArrivalDateTime:        null;
}

export interface METRCTransfersDeliveriesGET {
  Id:                               number;
  RecipientFacilityLicenseNumber:   string;
  RecipientFacilityName:            string;
  ShipmentTypeName:                 string;
  ShipmentTransactionType:          string;
  EstimatedDepartureDateTime:       string;
  ActualDepartureDateTime:          null;
  EstimatedArrivalDateTime:         string;
  ActualArrivalDateTime:            null;
  GrossWeight:                      null;
  GrossUnitOfWeightId:              null;
  GrossUnitOfWeightName:            null;
  PlannedRoute:                     string;
  DeliveryPackageCount:             number;
  DeliveryReceivedPackageCount:     number;
  ReceivedDateTime:                 string;
  EstimatedReturnDepartureDateTime: null;
  ActualReturnDepartureDateTime:    null;
  EstimatedReturnArrivalDateTime:   null;
  ActualReturnArrivalDateTime:      null;
  RejectedPackagesReturned:         boolean;
}

// Generated by https://quicktype.io

export interface METRCTransfersDeliveryPackagesGET {
  PackageId:                               number;
  PackageLabel:                            string;
  PackageType:                             string;
  SourceHarvestNames:                      null;
  SourcePackageLabels:                     null;
  ProductName:                             string;
  ProductCategoryName:                     string;
  ItemStrainName:                          null;
  ItemUnitCbdPercent:                      null;
  ItemUnitCbdContent:                      null;
  ItemUnitCbdContentUnitOfMeasureName:     null;
  ItemUnitCbdContentDose:                  null;
  ItemUnitCbdContentDoseUnitOfMeasureName: null;
  ItemUnitThcPercent:                      null;
  ItemUnitThcContent:                      null;
  ItemUnitThcContentUnitOfMeasureName:     null;
  ItemUnitThcContentDose:                  null;
  ItemUnitThcContentDoseUnitOfMeasureName: null;
  ItemUnitVolume:                          null;
  ItemUnitVolumeUnitOfMeasureName:         null;
  ItemUnitWeight:                          null;
  ItemUnitWeightUnitOfMeasureName:         null;
  ItemServingSize:                         null;
  ItemSupplyDurationDays:                  null;
  ItemUnitQuantity:                        null;
  ItemUnitQuantityUnitOfMeasureName:       null;
  LabTestingState:                         string;
  ProductionBatchNumber:                   null;
  IsTradeSample:                           boolean;
  IsDonation:                              boolean;
  SourcePackageIsDonation:                 boolean;
  IsTestingSample:                         boolean;
  ProductRequiresRemediation:              boolean;
  ContainsRemediatedProduct:               boolean;
  RemediationDate:                         null;
  ShipmentPackageState:                    string;
  ShippedQuantity:                         number;
  ShippedUnitOfMeasureName:                string;
  GrossUnitOfWeightName:                   null;
  ReceivedQuantity:                        number | null;
  ReceivedUnitOfMeasureName:               null | string;
}

// Generated by https://quicktype.io

export interface METRCTransfersDeliveryPackagesWholeSaleGET {
  PackageId:              number;
  PackageLabel:           string;
  ShipperWholesalePrice:  number | null;
  ReceiverWholesalePrice: number | null;
}

// Generated by https://quicktype.io

export interface METRCTransfersDeliveryPackagesRequiredLabTestBatchesGET {
  PackageId:        number;
  LabTestBatchId:   number;
  LabTestBatchName: string;
}

export interface METRCTransfersDeliveryPackagesStatesGet {}

// Generated by https://quicktype.io

export interface METRCTransfersExternalIncomingPOST {
  ShipperLicenseNumber:             string;
  ShipperName:                      string;
  ShipperMainPhoneNumber:           string;
  ShipperAddress1:                  string;
  ShipperAddress2:                  null;
  ShipperAddressCity:               string;
  ShipperAddressState:              string;
  ShipperAddressPostalCode:         null;
  TransporterFacilityLicenseNumber: null;
  DriverOccupationalLicenseNumber:  null;
  DriverName:                       null;
  DriverLicenseNumber:              null;
  PhoneNumberForQuestions:          null;
  VehicleMake:                      null;
  VehicleModel:                     null;
  VehicleLicensePlateNumber:        null;
  Destinations:                     Destination[];
}

export interface Destination {
  RecipientLicenseNumber:     string;
  TransferTypeName:           string;
  PlannedRoute:               string;
  EstimatedDepartureDateTime: string;
  EstimatedArrivalDateTime:   string;
  GrossWeight:                null;
  GrossUnitOfWeightId:        null;
  Transporters:               Transporter[];
  Packages:                   Package[];
}

export interface Package {
  ItemName:              string;
  Quantity:              number;
  UnitOfMeasureName:     string;
  PackagedDate:          string;
  GrossWeight:           null;
  GrossUnitOfWeightName: null;
  WholesalePrice:        null;
}

export interface Transporter {
  TransporterFacilityLicenseNumber: string;
  DriverOccupationalLicenseNumber:  string;
  DriverName:                       string;
  DriverLicenseNumber:              string;
  PhoneNumberForQuestions:          string;
  VehicleMake:                      string;
  VehicleModel:                     string;
  VehicleLicensePlateNumber:        string;
  IsLayover:                        boolean;
  EstimatedDepartureDateTime:       string;
  EstimatedArrivalDateTime:         string;
  TransporterDetails:               null;
}

// Generated by https://quicktype.io

export interface METRCTransfersExternalIncomingPUT {
  TransferId:                       number;
  ShipperLicenseNumber:             string;
  ShipperName:                      string;
  ShipperMainPhoneNumber:           null;
  ShipperAddress1:                  null;
  ShipperAddress2:                  null;
  ShipperAddressCity:               null;
  ShipperAddressState:              null;
  ShipperAddressPostalCode:         null;
  TransporterFacilityLicenseNumber: null;
  DriverOccupationalLicenseNumber:  null;
  DriverName:                       null;
  DriverLicenseNumber:              null;
  PhoneNumberForQuestions:          null;
  VehicleMake:                      null;
  VehicleModel:                     null;
  VehicleLicensePlateNumber:        null;
  Destinations:                     Destination[];
}

export interface Destination {
  TransferDestinationId:      null;
  RecipientLicenseNumber:     string;
  TransferTypeName:           string;
  PlannedRoute:               string;
  EstimatedDepartureDateTime: string;
  EstimatedArrivalDateTime:   string;
  GrossWeight:                null;
  GrossUnitOfWeightId:        null;
  Transporters:               Transporter[];
  Packages:                   Package[];
}

export interface Package {
  ItemName:              string;
  Quantity:              number;
  UnitOfMeasureName:     string;
  PackagedDate:          string;
  GrossWeight:           null;
  GrossUnitOfWeightName: null;
  WholesalePrice:        null;
}

export interface Transporter {
  TransporterFacilityLicenseNumber: string;
  DriverOccupationalLicenseNumber:  string;
  DriverName:                       string;
  DriverLicenseNumber:              string;
  PhoneNumberForQuestions:          string;
  VehicleMake:                      string;
  VehicleModel:                     string;
  VehicleLicensePlateNumber:        string;
  IsLayover:                        boolean;
  EstimatedDepartureDateTime:       string;
  EstimatedArrivalDateTime:         string;
  TransporterDetails:               null;
}

// Generated by https://quicktype.io

export interface METRCTransfersTemplatesGet {
  Id:                                 number;
  ManifestNumber:                     null;
  ShipmentLicenseType:                number;
  ShipperFacilityLicenseNumber:       string;
  ShipperFacilityName:                string;
  Name:                               string;
  TransporterFacilityLicenseNumber:   string;
  TransporterFacilityName:            string;
  DriverName:                         string;
  DriverOccupationalLicenseNumber:    string;
  DriverVehicleLicenseNumber:         string;
  VehicleMake:                        string;
  VehicleModel:                       string;
  VehicleLicensePlateNumber:          string;
  DeliveryCount:                      number;
  ReceivedDeliveryCount:              number;
  PackageCount:                       number;
  ReceivedPackageCount:               number;
  ContainsPlantPackage:               boolean;
  ContainsProductPackage:             boolean;
  ContainsTradeSample:                boolean;
  ContainsDonation:                   boolean;
  ContainsTestingSample:              boolean;
  ContainsProductRequiresRemediation: boolean;
  ContainsRemediatedProductPackage:   boolean;
  CreatedDateTime:                    string;
  CreatedByUserName:                  null;
  LastModified:                       string;
  DeliveryId:                         number;
  RecipientFacilityLicenseNumber:     null;
  RecipientFacilityName:              null;
  ShipmentTypeName:                   null;
  ShipmentTransactionType:            null;
  EstimatedDepartureDateTime:         string;
  ActualDepartureDateTime:            null;
  EstimatedArrivalDateTime:           string;
  ActualArrivalDateTime:              null;
  DeliveryPackageCount:               number;
  DeliveryReceivedPackageCount:       number;
  ReceivedDateTime:                   null;
  EstimatedReturnDepartureDateTime:   null;
  ActualReturnDepartureDateTime:      null;
  EstimatedReturnArrivalDateTime:     null;
  ActualReturnArrivalDateTime:        null;
}

// Generated by https://quicktype.io

export interface METRCTansfersTemplatesDeliveriesGet {
  Id:                               number;
  RecipientFacilityLicenseNumber:   string;
  RecipientFacilityName:            string;
  ShipmentTypeName:                 string;
  ShipmentTransactionType:          string;
  EstimatedDepartureDateTime:       string;
  ActualDepartureDateTime:          null;
  EstimatedArrivalDateTime:         string;
  ActualArrivalDateTime:            null;
  GrossWeight:                      null;
  GrossUnitOfWeightId:              null;
  GrossUnitOfWeightName:            null;
  PlannedRoute:                     string;
  DeliveryPackageCount:             number;
  DeliveryReceivedPackageCount:     number;
  ReceivedDateTime:                 string;
  EstimatedReturnDepartureDateTime: null;
  ActualReturnDepartureDateTime:    null;
  EstimatedReturnArrivalDateTime:   null;
  ActualReturnArrivalDateTime:      null;
  RejectedPackagesReturned:         boolean;
}


// Generated by https://quicktype.io

export interface MetrcTransfersTemplatesDeliveryPackagesGet {
  PackageId:                               number;
  PackageLabel:                            string;
  PackageType:                             string;
  SourceHarvestNames:                      null;
  SourcePackageLabels:                     null;
  ProductName:                             string;
  ProductCategoryName:                     string;
  ItemStrainName:                          null;
  ItemUnitCbdPercent:                      null;
  ItemUnitCbdContent:                      null;
  ItemUnitCbdContentUnitOfMeasureName:     null;
  ItemUnitCbdContentDose:                  null;
  ItemUnitCbdContentDoseUnitOfMeasureName: null;
  ItemUnitThcPercent:                      null;
  ItemUnitThcContent:                      null;
  ItemUnitThcContentUnitOfMeasureName:     null;
  ItemUnitThcContentDose:                  null;
  ItemUnitThcContentDoseUnitOfMeasureName: null;
  ItemUnitVolume:                          null;
  ItemUnitVolumeUnitOfMeasureName:         null;
  ItemUnitWeight:                          null;
  ItemUnitWeightUnitOfMeasureName:         null;
  ItemServingSize:                         null;
  ItemSupplyDurationDays:                  null;
  ItemUnitQuantity:                        null;
  ItemUnitQuantityUnitOfMeasureName:       null;
  LabTestingState:                         string;
  ProductionBatchNumber:                   null;
  IsTradeSample:                           boolean;
  IsDonation:                              boolean;
  SourcePackageIsDonation:                 boolean;
  IsTestingSample:                         boolean;
  ProductRequiresRemediation:              boolean;
  ContainsRemediatedProduct:               boolean;
  RemediationDate:                         null;
  ShipmentPackageState:                    string;
  ShippedQuantity:                         number;
  ShippedUnitOfMeasureName:                string;
  GrossUnitOfWeightName:                   null;
  ReceivedQuantity:                        number | null;
  ReceivedUnitOfMeasureName:               null | string;
}

// Generated by https://quicktype.io

export interface METRCTransfersTemplatesPOST {
  Name:                             string;
  TransporterFacilityLicenseNumber: null;
  DriverOccupationalLicenseNumber:  null;
  DriverName:                       null;
  DriverLicenseNumber:              null;
  PhoneNumberForQuestions:          null;
  VehicleMake:                      null;
  VehicleModel:                     null;
  VehicleLicensePlateNumber:        null;
  Destinations:                     Destination[];
}

export interface Destination {
  RecipientLicenseNumber:     string;
  TransferTypeName:           string;
  PlannedRoute:               string;
  EstimatedDepartureDateTime: string;
  EstimatedArrivalDateTime:   string;
  Transporters:               Transporter[];
  Packages:                   Package[];
}

export interface Package {
  PackageLabel:   string;
  WholesalePrice: null;
}

export interface Transporter {
  TransporterFacilityLicenseNumber: string;
  DriverOccupationalLicenseNumber:  string;
  DriverName:                       string;
  DriverLicenseNumber:              string;
  PhoneNumberForQuestions:          string;
  VehicleMake:                      string;
  VehicleModel:                     string;
  VehicleLicensePlateNumber:        string;
  IsLayover:                        boolean;
  EstimatedDepartureDateTime:       string;
  EstimatedArrivalDateTime:         string;
  TransporterDetails:               null;
}

// Generated by https://quicktype.io

export interface METRCTransfersTemplatesPUT {
  TransferTemplateId:               number;
  Name:                             string;
  TransporterFacilityLicenseNumber: null;
  DriverOccupationalLicenseNumber:  null;
  DriverName:                       null;
  DriverLicenseNumber:              null;
  PhoneNumberForQuestions:          null;
  VehicleMake:                      null;
  VehicleModel:                     null;
  VehicleLicensePlateNumber:        null;
  Destinations:                     Destinations[];
}

export interface Destinations {
  TransferDestinationId:      number;
  RecipientLicenseNumber:     string;
  TransferTypeName:           string;
  PlannedRoute:               string;
  EstimatedDepartureDateTime: string;
  EstimatedArrivalDateTime:   string;
  Transporters:               Transporter[];
  Packages:                   Package[];
}

export interface Package {
  PackageLabel:   string;
  WholesalePrice: null;
}

export interface Transporter {
  TransporterFacilityLicenseNumber: string;
  DriverOccupationalLicenseNumber:  string;
  DriverName:                       string;
  DriverLicenseNumber:              string;
  PhoneNumberForQuestions:          string;
  VehicleMake:                      string;
  VehicleModel:                     string;
  VehicleLicensePlateNumber:        string;
  IsLayover:                        boolean;
  EstimatedDepartureDateTime:       string;
  EstimatedArrivalDateTime:         string;
  TransporterDetails:               null;
}

// Generated by https://quicktype.io

export interface METRCTransfersTypesGet {
  Name:                           string;
  ForLicensedShipments:           boolean;
  ForExternalIncomingShipments:   boolean;
  ForExternalOutgoingShipments:   boolean;
  RequiresDestinationGrossWeight: boolean;
  RequiresPackagesGrossWeight:    boolean;
}
