// Generated by https://quicktype.io

export interface TriposResult {
  approvedAmount:        number;
  convenienceFeeAmount:  number;
  subTotalAmount:        number;
  tipAmount:             number;
  fsaCard:               string;
  isCardInserted:        boolean;
  networkTransactionId:  string;
  creditSurchargeAmount: number;
  accountNumber:         string;
  binValue:              string;
  cardLogo:              string;
  currencyCode:          string;
  countryCode:           string;
  language:              string;
  entryMode:             string;
  expirationYear:        string;
  expirationMonth:       string;
  paymentType:           string;
  pinVerified:           boolean;
  signature:             Signature;
  terminalId:            string;
  totalAmount:           number;
  balanceAmount:         number;
  balanceCurrencyCode:   string;
  preReadId:             string;
  approvalNumber:        string;
  isApproved:            boolean;
  _processor:            Processor;
  statusCode:            string;
  transactionDateTime:   string;
  transactionId:         string;
  merchantId:            string;
  isOffline:             boolean;
  exceptionMessage: string;
  _errors:               any[];
  _hasErrors:            boolean;
  _links:                Link[];
  _logs:                 any[];
  _type:                 string;
  _warnings:             any[];
}

export interface Link {
  href:   string;
  method: string;
  rel:    string;
}

export interface Processor {
  processorLogs:               string[];
  processorRawResponse:        string;
  processorReferenceNumber:    string;
  processorRequestFailed:      boolean;
  processorRequestWasApproved: boolean;
  processorResponseCode:       string;
  processorResponseMessage:    string;
  expressResponseCode:         string;
  expressResponseMessage:      string;
  hostResponseCode:            string;
  logs:                        string[];
  rawResponse:                 string;
  processorName:               string;
}

export interface Signature {
  statusCode: string;
}

// Generated by https://quicktype.io

export interface ITriPOSPatch {
  allowDebit:                                     boolean;
  allowPartialApprovals:                          boolean;
  cashbackOptions:                                CashbackOptions;
  checkForDuplicateTransactions:                  boolean;
  confirmConvenienceFeeAmount:                    boolean;
  confirmOriginalAmount:                          boolean;
  contactlessEmvEnabled:                          string;
  contactlessEventDelayTime:                      number;
  contactlessMsdEnabled:                          string;
  countryCode:                                    string;
  creditAvsEntryCondition:                        string;
  currencyCode:                                   string;
  debitSurchargeAmount:                           number;
  emvFallbackAllowed:                             string;
  isCSCSupported:                                 string;
  isCashbackAllowed:                              boolean;
  isConfirmTotalAmountScreenDisplayed:            boolean;
  isDebitRefundSupported:                         boolean;
  isDisplayCustomAidScreen:                       boolean;
  isEbtCashBenefitSupported:                      boolean;
  isEbtFoodStampSupported:                        boolean;
  isEbtRefundSupported:                           boolean;
  isEmvSupported:                                 boolean;
  isGiftSupported:                                string;
  isHealthcareSupported:                          boolean;
  isManualEntryAllowed:                           string;
  isTipAllowed:                                   boolean;
  isTipPromptAllowed:                             boolean;
  language:                                       string;
  marketCode:                                     string;
  preferredAid:                                   string;
  processMaestroDebitAidWithOffLinePinCvmAsDebit: string;
  processor:                                      string;
  provisionalAmount:                              string;
  quickChipDataLifetime:                          string;
  quickChipEnabled:                               string;
  rebootTime:                                     string;
  signatureFormat:                                string;
  thresholdAmount:                                number;
  tipSelections:                                  string;
  userInputTimeout:                               string;
}

export interface CashbackOptions {
  manualEntry:      ManualEntry;
  selectionAmounts: string;
}

export interface ManualEntry {
}
