// Generated by https://quicktype.io
//CCS Export
export interface IMETRCSales {
  quantity:       number;
  unitPrice:      number;
  sku:            string;
  serialCode:     string;
  unitType:       string;
  productName:    string;
  metrcUnit:      string;
  batchDate:      string;
  metrcDate:      string;
  metrcResponse:  string;
  discountTotal:  number;
  id:             number;
  productID:      number;
  completionDate: string;
}
