import { Type } from "@angular/core";
import { IPagedList } from "src/app/_services/system/paging.service";

export interface PriceAdjustScheduleTypes {
  id         : number;
  name       : string;
  icon       : string;// Generated by https://quicktype.io
  value      : number;
  description: string;
 }

 // Generated by https://quicktype.io

export interface PS_SearchResultsPaged {

  results: IPriceSearchModel[];
  paging: IPagedList
}

export interface IPriceSearchModel {
  id:                 number;
  allEligible:        boolean;
  allOrderTypes:      boolean;
  allWeekdaysDays:    boolean;
  timeFrameAlways:    boolean;
  allDates:           boolean;
  active:             boolean;
  name:               string;
  created:            string;
  lastEdited:         string;
  type:               string;
  value:              number;
  pageNumber:         number;
  pageSize:           number;
}

export interface IPriceSchedule {
  id:                 number;
  allEligible:        boolean;
  allOrderTypes:      boolean;
  allWeekdaysDays:    boolean;
  timeFrameAlways:    boolean;
  allDates:           boolean;
  active:             boolean;
  name:               string;
  created:            string;
  lastEdited:         string;
  type:               string;
  value:              number;
  dateFrames:         DateFrame[];
  weekDays:           WeekDay[];
  clientTypes:        ClientType[];
  orderTypes:         OrderType[];
  timeFrames:         TimeFrame[];
  requiredCategories: DiscountInfo[];
  brandDiscounts:     DiscountInfo[];
  categoryDiscounts:  DiscountInfo[];
  itemDiscounts:      DiscountInfo[];
  itemTypeDiscounts:  DiscountInfo[];
  requiredBrands:     DiscountInfo[];
  requiredItemTypes:  DiscountInfo[];
  requiredItems:      DiscountInfo[];
}

export interface DiscountInfo {
  id:       number;
  value:    number;
  quantity: number;
  itemID:   number;
  andOr:    AndOr;
  name:     string;
  allItems: boolean;
  typeID?:  number;
  privateScheduleID: number;
  sort:     number;
}

export enum AndOr {
  SampleString4 = "sample string 4",
  SampleString5 = "sample string 5",
}

export interface ClientType {
  id:              number;
  priceScheduleID: number;
  clientTypeID:    number;
  // type:            ItemType;
  name:            string;
  privateScheduleID: number;
}

export interface DateFrame {
  id:              number;
  priceScheduleID: number;
  startDate:       string;
  endDate:         string;
  privateScheduleID: number;
}

export interface OrderType {
  id:              number;
  priceScheduleID: number;
  orderTypeID:     number;
  name:            string;
  // type:            ItemType;
  privateScheduleID: number;
}

export interface TimeFrame {
  id:              number;
  priceScheduleID: number;
  startTime:       string;
  endTime:         string;
  privateScheduleID: number;
}

export interface WeekDay {
  id:              number;
  priceScheduleID: number;
  name:            string;
  privateScheduleID: number;
}


export interface ItemType {
  id:             number;
  name:           string
}

// Generated by https://quicktype.io

// export interface IPriceSchedule {
//   id:                 number;
//   allEligible:        boolean;
//   allOrderTypes:      boolean;
//   allWeekdaysDays:    boolean;
//   timeFrameAlways:    boolean;
//   allDates:           boolean;
//   active:             boolean;
//   name:               string;
//   created:            string;
//   lastEdited:         string;
//   type:               string;
//   value:              number;
//   dateFrames:         DateFrame[];
//   weekDays:           WeekDay[];
//   clientTypes:        ClientType[];
//   orderTypes:         OrderType[];
//   timeFrames:         TimeFrame[];
//   requiredCategories: DiscountInfo[];
//   brandDiscounts:     DiscountInfo[];
//   categoryDiscounts:  DiscountInfo[];
//   itemDiscounts:      DiscountInfo[];
//   itemTypeDiscounts:  DiscountInfo[];
//   requiredBrands:     DiscountInfo[];
//   requiredItemTypes:  DiscountInfo[];
//   requiredItems:      DiscountInfo[];
// }

// export interface DiscountInfo {
//   id:       number;
//   value:    number;
//   quantity: number;
//   itemID:   number;
//   andOr:    string;
//   name:     string;
//   allItems: boolean;
// }

// export interface ClientType {
//   id:              number;
//   priceScheduleID: number;
//   clientTypeID:    number;
// }

// export interface DateFrame {
//   id:              number;
//   priceScheduleID: number;
//   startDate:       string;
//   endDate:         string;
// }

// export interface OrderType {
//   id:              number;
//   priceScheduleID: number;
//   orderTypeID:     number;
// }

// export interface TimeFrame {
//   id:              number;
//   priceScheduleID: number;
//   startTime:       string;
//   endTime:         string;
// }

// export interface WeekDay {
//   id:              number;
//   priceScheduleID: number;
//   name:            string;
// }
