import { IMenuItem } from 'src/app/_interfaces/menu/menu-products';
import { IPurchaseOrderItem, PosOrderItem } from '..';
// Generated by https://quicktype.io

export interface IPromptGroup {
  id:                       number;
  name:                     string;
  created:                  string;
  lastEdited:               string;
  image:                    string;
  instructions:             string;
  selected_PromptSubGroups: SelectedPromptSubGroup[];
  posOrderItem              : IPurchaseOrderItem;
  orderID                   : number;
  currentAccordionStep      : number;
  splitGroupID              : number;
}

export interface SelectedPromptSubGroup {
  promptGroupsID:    number;
  promptSubGroupsID: number;
  id:                number;
  sortOrder:         number;
  promptSubGroups:   PromptSubGroups;
}

export interface PromptSubGroups {
  id:                number;
  name:              string;
  minQuantity:       number;
  maxQuantity:       number;
  moveOnQuantity:    number;
  created:           string;
  lastEdited:        string;
  instructions:      string;
  image:             string;
  promptMenuItems  : PromptMenuItem[];
  itemsSelected    : MenuItemsSelected[];
  quantityMet      : boolean;
  minQuantityMet   : boolean;
  maxQuantityMet   : boolean;
  hideSplitOptions : boolean;
}

export interface PromptMenuItem {
  id:                number;
  promptSubGroupsID: number;
  menuItemID:        number;
  sortOrder:         number;
  prompt_Products:   PromptProducts;
}

export interface PromptProducts {
  id                    : number;
  name                  : string;
  unitTypeID            : number;
  itemTypeID            : number;
  priceCategory         : number;
  productCount          : number;
  promptID              : number;
  urlImageMain          : string;
  onlineShortDescription: string;
  prodSecondLanguage    : string;
}


export interface MenuItemsSelected {
	 menuItem         : IMenuItem;
	 unitTypeID       : number;
	 quantity         : number;
	 price            : number;
	 orderPromptGroup : IPromptGroup;
}

// Generated by https://quicktype.io

// export interface IPromptSubGroup {
//   id:              number;
//   name:            string;
//   minQuantity:     number;
//   maxQuantity:     number;
//   moveOnQuantity:  number;
//   created:         string;
//   lastEdited:      string;
//   instructions:                string;
//   image       :                string;
//   promptMenuItems: PromptMenuItem[];
// }

// export interface PromptMenuItem {
//   id:                number;
//   promptSubGroupsID: number;
//   menuItemID:        number;
//   sortOrder:         number;
//   prompt_Products:   PromptProducts;
// }

// export interface PromptProducts {
//   id:            number;
//   name:          string;
//   unitTypeID:    number;
//   itemTypeID:    number;
//   priceCategory: number;
//   productCount:  number;
//   menuName:      number;
// }

