import { IMenuItem } from 'src/app/_interfaces/menu/menu-products';
import { IProduct, IPurchaseOrderItem, PosOrderItem, ProductPrice } from '..';
// Generated by https://quicktype.io

export interface IPromptGroup {
  id:                       number;
  name:                     string;
  created:                  string;
  lastEdited:               string;
  image:                    string;
  instructions:             string;
  selected_PromptSubGroups  : SelectedPromptSubGroup[];
  posOrderItem              : IPurchaseOrderItem;
  orderID                   : number;
  currentAccordionStep      : number;
  splitGroupID              : number;
}

export interface SelectedPromptSubGroup {
  promptGroupsID:    number;
  promptSubGroupsID: number;
  id:                number;
  sortOrder:         number;
  promptSubGroups:   PromptSubGroups;
}

export interface PromptSubGroups {
  id:                number;
  name:              string;
  minQuantity:       number;
  maxQuantity:       number;
  moveOnQuantity:    number;
  created:           string;
  lastEdited:        string;
  instructions:      string;
  image:             string;
  promptMenuItems  : PromptMenuItem[];
  itemsSelected    : MenuItemsSelected[];
  quantityMet      : boolean;
  minQuantityMet   : boolean;
  maxQuantityMet   : boolean;
  hideSplitOptions : boolean;
  freePage         : boolean;
  json: string;
}

export interface IPromptSubProperites {
  itemModList: string;
}

export interface PromptMenuItem {
  id:                number;
  promptSubGroupsID: number;
  menuItemID:        number;
  sortOrder:         number;
  prompt_Products:   PromptProducts;
}

export interface PromptProductsOld {
  id                    : number;
  name                  : string;
  unitTypeID            : number;
  itemTypeID            : number;
  priceCategory         : number;
  productCount          : number;
  promptID              : number;
  urlImageMain          : string;
  onlineShortDescription: string;
  prodSecondLanguage    : string;
}

export interface PromptProducts {
  id: number | null;
  name: string;
  unitTypeId: number | null;
  itemTypeId: number | null;
  priceCategory: number | null;
  productCount: number | null;
  promptGroupId: number | null;
  urlImageMain: string;
  onlineShortDescription: string;
  active: boolean | null;
  thcContent: number | null;
  glutenFree: boolean | null;
  icon: string;
  terpenes: string;
  childProof: boolean | null;
  mgchd: number | null;
  mgtch: number | null;
  parLevel: number | null;
  allergens: string;
  priceScheduleId: number | null;
  slug: string;
  prodSecondLanguage: string;
  paymentId: number | null;
  json: string;
  pbMainId: number | null;
  thumbnail: string;
  pieceWeight: number | null;
}
export interface MenuItemsSelected {
	 menuItem         : IMenuItem;
	 unitTypeID       : number;
	 quantity         : number;
	 price            : number;
	 orderPromptGroup : IPromptGroup;
   productPrice:      ProductPrice;
}

