import { AfterViewInit,Component, OnInit, QueryList, ViewChildren } from '@angular/core';
import { SchemaUpdateResults, SystemService } from 'src/app/_services/system/system.service';
import { forkJoin, Observable, of, switchMap } from 'rxjs';
import { SitesService } from 'src/app/_services/reporting/sites.service';
import { SettingsService } from 'src/app/_services/system/settings.service';
import { ISetting } from 'src/app/_interfaces';
import { TransferDataService } from 'src/app/_services/transactions/transfer-data.service';
import { DateHelperService } from 'src/app/_services/reporting/date-helper.service';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-database-schema',
  templateUrl: './database-schema.component.html',
  styleUrls: ['./database-schema.component.scss'],
  // changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DatabaseSchemaComponent implements AfterViewInit, OnInit{
  manageData:boolean;

  version$: Observable<ISetting>;
  apiVersion$: Observable<string>;
  updateSections = ['GetSyncDatabaseSchema', 'CreateAPIViews', 'CreateViews', 'CreateTablesA', 'CreateTablesB', 'createAPIReportviews']
  schemaResults : any[] ;
  schema$:              Observable<SchemaUpdateResults[]>;
  schema:               SchemaUpdateResults[];
  completed:            string;
  @ViewChildren('allTheseThings') things: QueryList<any>;
  action$:Observable<any>;
  processingVisible :    boolean;
  databaseMessage   :    string;
  closeDateForm: FormGroup
  constructor(
              private systemService:     SystemService,
              private sitesService:      SitesService,
              private settingService: SettingsService,
              private dateHelper : DateHelperService,
              private fb: FormBuilder,
              private transferData: TransferDataService,
             )
  {
    // console.log('')
  }

  ngOnInit() {
    const site = this.sitesService.getAssignedSite();
    this.apiVersion$ = this.systemService.getAPIVersion(site);
    this.version$ = this.settingService.getSettingByName(site, 'PointlessAPIVersion');
    this.initDateForm()
  }


  initDateForm() {
    this.closeDateForm = this.fb.group({
      date: []
    })
  }
   ngAfterViewInit() {
    this.things.changes.subscribe(t => {
      this.ngForRendred();
    })
  }

  ngForRendred() {
    this.processingVisible   =  false
    if (this.schema){
      this.databaseMessage   = `Database updated,  ${this.schema[0].errorCount} errors.`
    }
  }

  updateSchema() {
    this.processingVisible = true
    const site = this.sitesService.getAssignedSite();
    const user = JSON.parse(localStorage.getItem('user'))
    console.log('user', user)
    this.schema$ = this.systemService.getSyncDatabaseSchema(site).pipe(switchMap(data =>
      {
        this.schema = data
        this.processingVisible   =  false
        return of(data)
      }
    ))
  }

  cleanData() {
    this.processingVisible = true
    const site = this.sitesService.getAssignedSite();


    this.action$  =   this.systemService.cleanData(site).pipe(
      switchMap( data=> {
        this.schema = data// Generated by https://quicktype.io



        this.processingVisible   =  false
        return of(data)
    }))
  }

  closeByDate() {
    this.processingVisible = true
    const site = this.sitesService.getAssignedSite();

    const date = this.closeDateForm.controls['date'].value;
    console.log(date)
    let formattedDate = this.dateHelper.format(date, 'medium').toString()
    console.log('medium', formattedDate)
    console.log('mmddyyyy', this.dateHelper.format(date, 'MM/dd/yyyy').toString())
    // gets the selected date
    const closeDate = this.dateHelper.format(date, 'MM/dd/yyyy').toString()
    console.log('close data', closeDate)
    this.action$ =  this.transferData.closeByDate(site, closeDate, closeDate).pipe(switchMap(data => {
      this.sitesService.notify('Date has been archived', 'Close', 5000, 'green')
      this.processingVisible = false
      return of(data  )
    }))
  }

  updateSchemArray() {
    this.processingVisible = true
    const site = this.sitesService.getAssignedSite();
    let observables  = this.updateSections.map( section =>  this.systemService.updateDatabase(site, section) )
    let source = forkJoin(observables);
    source.subscribe(data => {
      console.log(data)
      this.schemaResults.push(data)
    });
  }


}
