// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface IDriversLicense {
  failureMessage:  string;
  accountNumber:  string;
  firstName:      string;
  middleName:     string;
  lastName:       string;
  address:        string;
  state:          string;
  city:           string;
  zip:            string;
  cityStateZip:   CityStateZip;
  dob:            string;
  exp:            string;
  fileName:       string;
}

export interface CityStateZip {
}
