// Generated by https://quicktype.io

export interface EmployeeClock {
  breaks:           employeeBreak[];
  id:               number;
  employeeID:       number;
  logInTime:        string;
  logInDate:        string;
  logOutTime:       string;
  logOutDate:       string;
  note:             null;
  active:           null;
  periodID:         null;
  employeePosition: number;
  payRate:          number;
  employeMealCount: null;
  regHours:         number;
  otHours:          number | null;
  regPay:           number;
  otPay:            number | null;
  employeeName:     string;
  breakMinutes:     null;
  originalClockIn:  string;
  originalClockOut: null;
  managerID:        null;
  shiftID:          null;
  shiftName:        null;
  siteID:           null;
}

export interface employeeBreak {
  id:                number;
  logID:             number;
  timeStart:         string;
  breakIdentifierID: number;
  timeEnd:           string;
}
